from aiogram.types import ReplyKeyboardRemove, ReplyKeyboardMarkup, KeyboardButton, InlineKeyboardMarkup, InlineKeyboardButton

#Продолжить
cont = KeyboardButton('Продолжить')
cont_kb = ReplyKeyboardMarkup(resize_keyboard=True)
cont_kb.add(cont)

#Стартовая клавиатура
d800 = KeyboardButton('800')
d900 = KeyboardButton('900')
d1000 = KeyboardButton('1000')
d1100 = KeyboardButton('1100')
d1200 = KeyboardButton('1200')
d1300 = KeyboardButton('1300')
d1400 = KeyboardButton('1400')
d1500 = KeyboardButton('1500')
d1600 = KeyboardButton('1600')
d1700 = KeyboardButton('1700')
d1800 = KeyboardButton('1800')
d1900 = KeyboardButton('1900')
d2000 = KeyboardButton('2000')
start_kb = ReplyKeyboardMarkup(resize_keyboard=True)
start_kb.add(d800)
start_kb.add(d900)
start_kb.add(d1000)
start_kb.add(d1100)
start_kb.add(d1200)
start_kb.add(d1300)
start_kb.add(d1400)
start_kb.add(d1500)
start_kb.add(d1600)
start_kb.add(d1700)
start_kb.add(d1800)
start_kb.add(d1900)
start_kb.add(d2000)

#Темы
math = KeyboardButton('Математика')
real = KeyboardButton('Реализация')
str = KeyboardButton('Строки')
teorch = KeyboardButton('Теория чисел')
trees = KeyboardButton('Деревья')
graph = KeyboardButton('Графы')
sort = KeyboardButton('Сортировки')
konst = KeyboardButton('Конструктив')
pereb = KeyboardButton('Перебор')
geom = KeyboardButton('Геометрия')
theme_kb = ReplyKeyboardMarkup(resize_keyboard=True)
theme_kb.add(math)
theme_kb.add(real)
theme_kb.add(str)
theme_kb.add(teorch)
theme_kb.add(trees)
theme_kb.add(graph)
theme_kb.add(konst)
theme_kb.add(sort)
theme_kb.add(pereb)
theme_kb.add(geom)

#Начать заново
retur = KeyboardButton('Искать заново')
return_kb = ReplyKeyboardMarkup(resize_keyboard=True)
return_kb.add(retur)
